---


- name: galaxy.cis
  src: https://github.com/MindPointGroup/RHEL7-CIS.git

- name: galaxy.fail2ban
  src: https://github.com/resmo/ansible-role-fail2ban.git

#- name: galaxy.lvm
#  src: https://github.com/debops/ansible-lvm.git


