#!/usr/bin/env bash
set -e

# pip install --upgrade ansible
# pip install --upgrade boto3
# pip install --upgrade --user awscli

# install deps
#ansible-galaxy install --roles-path=./roles -r requirements.yml

# Decrypt
#ansible-vault decrypt group_vars/all/secrets.yml --vault-password-file ~/.vault_password_farrell

# Encrypt
#ansible-vault encrypt group_vars/all/secrets.yml --vault-password-file ~/.vault_password_farrell

# Cloud
ansible-playbook playbook.yml --vault-password-file ~/.vault_password_farrell

