#!/usr/bin/env bash
set -e

# pip install --upgrade ansible
# pip install --upgrade boto3
# pip install --upgrade --user awscli

# install deps
#ansible-galaxy install --roles-path=./roles -r requirements.yml

# Cloud
#ansible-playbook 1_aws.yml

# Servers
ansible bastion -m ping

ansible-playbook 2_servers.yml